# Generated by Django 5.1.3 on 2026-10-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchallenge',
            name='purpose',
            field=models.CharField(choices=[('confirm', 'confirm'), ('magic', 'magic'), ('reset', 'reset'), ('notice', 'notice')], max_length=10),
        ),
    ]
