# Generated by Django 5.1.3 on 2026-10-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailchallenge_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchallenge',
            name='to_new_address',
            field=models.BooleanField(default=False),
        ),
    ]
