# Generated by Django 5.1.3 on 2026-10-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pending_links_and_pools'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchallenge',
            name='accepts_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='news_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='news_opt_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='terms_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
