# Generated by Django 5.1.3 on 2026-10-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchallenge',
            name='public_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
