# Generated by Django 5.1.3 on 2026-10-02 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('instagram_handle', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicbrainz_offset', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('cover_art_url', models.URLField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(max_length=36, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='catalog.album')),
            ],
        ),
    ]
