# Generated by Django 5.1.3 on 2026-10-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ensure_syncstate_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='deezer_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='album',
            name='release_type',
            field=models.CharField(choices=[('album', 'Álbum'), ('ep', 'EP'), ('single', 'Single')], default='album', max_length=10),
        ),
        migrations.AddField(
            model_name='artist',
            name='deezer_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='deezer_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='song',
            name='deezer_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='mbid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='mbid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
