# Generated by Django 5.1.3 on 2026-10-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_enable_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='hidden_reason',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
