# Generated by Django 5.1.3 on 2026-10-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_song_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='picture_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='picture_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
