# Generated by Django 5.1.3 on 2026-10-06 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_artist_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('image_type', models.CharField(max_length=20)),
                ('position', models.PositiveIntegerField(default=0, help_text='Menor número = aparece primero.')),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='catalog.artist')),
            ],
            options={
                'verbose_name': 'artista destacado',
                'verbose_name_plural': 'artistas destacados',
                'ordering': ['position', 'id'],
            },
        ),
    ]
