# Generated by Django 5.1.3 on 2026-10-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_featured_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='deezer_source',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='artist',
            name='deezer_status',
            field=models.CharField(blank=True, db_index=True, max_length=15),
        ),
        migrations.AddField(
            model_name='artist',
            name='deezer_suggested_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
