# Generated by Django 5.1.3 on 2026-10-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_deezer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('error', 'Algo está mal'), ('alta', 'Quiere sumarse'), ('contacto', 'Mensaje')], max_length=10)),
                ('target_type', models.CharField(blank=True, choices=[('artist', 'Artista'), ('album', 'Disco'), ('song', 'Canción')], max_length=10)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('links', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('nuevo', 'Nuevo'), ('visto', 'Visto'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado')], db_index=True, default='nuevo', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'reporte o pedido',
                'verbose_name_plural': 'reportes y pedidos',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
