# Generated by Django 5.1.3 on 2026-10-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='reason',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
