# Generated by Django 5.1.3 on 2026-10-06 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_submission_reason_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('content_type', models.CharField(default='image/webp', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.submission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
