# Generated by Django 5.1.3 on 2026-10-05 21:37

import battles.models
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_artist_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=battles.models.new_code, max_length=8, unique=True)),
                ('host_token', models.CharField(default=battles.models.new_host_token, max_length=64)),
                ('host_device_id', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('lobby', 'En espera'), ('playing', 'Jugando'), ('finished', 'Terminada')], db_index=True, default='lobby', max_length=10)),
                ('round_count', models.PositiveSmallIntegerField()),
                ('round_seconds', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('host_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_battles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattlePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('display_name', models.CharField(max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='battles.battle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BattleRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='battles.battle')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.song')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='BattleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('received_at', models.DateTimeField()),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('song_guessed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.song')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='battles.battleplayer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='battles.battleround')),
            ],
        ),
        migrations.AddConstraint(
            model_name='battleplayer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('display_name'), models.F('battle'), name='battle_player_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='battleplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('battle', 'user'), name='battle_player_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='battleplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('device_id', ''), _negated=True)), fields=('battle', 'device_id'), name='battle_player_device_unique'),
        ),
        migrations.AddConstraint(
            model_name='battleround',
            constraint=models.UniqueConstraint(fields=('battle', 'index'), name='battle_round_index_unique'),
        ),
        migrations.AddConstraint(
            model_name='battleanswer',
            constraint=models.UniqueConstraint(fields=('round', 'player'), name='battle_answer_once'),
        ),
    ]
