# Generated by Django 5.1.3 on 2026-10-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='audio_mode',
            field=models.CharField(choices=[('each', 'En cada dispositivo'), ('host', 'En el dispositivo del anfitrión')], default='each', max_length=10),
        ),
        migrations.AddField(
            model_name='battle',
            name='join_mode',
            field=models.CharField(choices=[('open', 'Cualquiera con el enlace'), ('approval', 'Con aprobación')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='battleplayer',
            name='status',
            field=models.CharField(choices=[('accepted', 'Aceptado'), ('pending', 'Esperando'), ('rejected', 'Rechazado')], default='accepted', max_length=10),
        ),
    ]
