# Generated by Django 5.1.3 on 2026-10-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_modes_and_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='battle',
            name='playlist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='battle',
            name='songs_mode',
            field=models.CharField(choices=[('random', 'Al azar'), ('list', 'Lista elegida')], default='random', max_length=10),
        ),
        migrations.AddField(
            model_name='battleround',
            name='source',
            field=models.CharField(default='deezer', max_length=10),
        ),
        migrations.AddField(
            model_name='battleround',
            name='start_seconds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battleround',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
