# Generated by Django 5.1.3 on 2026-10-05 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_songs_modes_and_round_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='team_mode',
            field=models.CharField(choices=[('none', 'Sin equipos'), ('random', 'Equipos al azar'), ('manual', 'Equipos armados')], default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='BattleTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='battles.battle')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='battleplayer',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='battles.battleteam'),
        ),
        migrations.AddConstraint(
            model_name='battleteam',
            constraint=models.UniqueConstraint(fields=('battle', 'index'), name='battle_team_index_unique'),
        ),
    ]
