# Generated by Django 5.1.3 on 2026-10-02 20:37

import django.db.models.deletion
import gameplay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_ensure_syncstate_singleton'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('state', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=10)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_appearances', to='catalog.song')),
            ],
        ),
        migrations.CreateModel(
            name='GuessAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('guessed_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('feedback', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='gameplay.dailysong')),
            ],
            options={
                'ordering': ['attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=50)),
                ('score', models.PositiveIntegerField()),
                ('winning_attempt', models.PositiveSmallIntegerField()),
                ('total_time_seconds', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='gameplay.dailysong')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device_id', 'daily_song'), name='one_score_per_device_per_day')],
            },
        ),
        migrations.CreateModel(
            name='Stem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem_type', models.CharField(choices=[('drums', 'Batería'), ('bass', 'Bajo'), ('vocals', 'Voz'), ('other', 'Otros')], max_length=10)),
                ('unlock_order', models.PositiveSmallIntegerField()),
                ('audio_file', models.FileField(storage=gameplay.models.get_stems_storage, upload_to=gameplay.models.stem_upload_path)),
                ('daily_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stems', to='gameplay.dailysong')),
            ],
            options={
                'ordering': ['unlock_order'],
                'constraints': [models.UniqueConstraint(fields=('daily_song', 'unlock_order'), name='unique_unlock_order_per_day')],
            },
        ),
    ]
