# Generated by Django 5.1.3 on 2026-10-02 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stem',
            name='unlock_order',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddConstraint(
            model_name='stem',
            constraint=models.UniqueConstraint(fields=('daily_song', 'stem_type'), name='unique_stem_type_per_day'),
        ),
        migrations.AddConstraint(
            model_name='stem',
            constraint=models.CheckConstraint(condition=models.Q(('unlock_order__gte', 1), ('unlock_order__lte', 4)), name='unlock_order_between_1_and_4'),
        ),
    ]
