# Generated by Django 5.1.3 on 2026-10-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_alter_stem_unlock_order_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guessattempt',
            constraint=models.UniqueConstraint(fields=('device_id', 'daily_song', 'attempt_number'), name='unique_attempt_number_per_device_per_day'),
        ),
    ]
