# Generated by Django 5.1.3 on 2026-10-04 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_guessattempt_unique_attempt_number_per_device_per_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guessattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoreentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='guessattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'daily_song', 'attempt_number'), name='unique_attempt_number_per_user_per_day'),
        ),
        migrations.AddConstraint(
            model_name='scoreentry',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'daily_song'), name='one_score_per_user_per_day'),
        ),
    ]
