# Generated by Django 5.1.3 on 2026-10-04 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_attempts_and_scores_belong_to_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guessattempt',
            name='unique_attempt_number_per_device_per_day',
        ),
        migrations.RemoveConstraint(
            model_name='scoreentry',
            name='one_score_per_device_per_day',
        ),
        migrations.AddConstraint(
            model_name='guessattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('device_id', 'daily_song', 'attempt_number'), name='unique_attempt_number_per_device_per_day'),
        ),
        migrations.AddConstraint(
            model_name='scoreentry',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('device_id', 'daily_song'), name='one_score_per_device_per_day'),
        ),
    ]
