# Generated by Django 5.1.3 on 2026-10-04 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_deezer_ids'),
        ('gameplay', '0005_device_uniqueness_only_without_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessattempt',
            name='guessed_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.song'),
        ),
    ]
