# Generated by Django 5.1.3 on 2026-10-04 07:21

import django.db.models.deletion
import django.db.models.functions.text
import gameplay.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0006_guessattempt_guessed_song'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, default='', max_length=64)),
                ('public_name', models.CharField(blank=True, max_length=50, null=True)),
                ('played', models.PositiveIntegerField(default=0)),
                ('won', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('max_streak', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('distribution', models.JSONField(default=gameplay.models.empty_distribution)),
                ('last_played_day', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('device_id',), name='one_stats_row_per_anonymous_device'), models.UniqueConstraint(django.db.models.functions.text.Lower('public_name'), condition=models.Q(('public_name__isnull', False)), name='public_name_is_unique_whatever_the_case'), models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('device_id', ''), _negated=True), _connector='OR'), name='stats_row_has_an_owner')],
            },
        ),
    ]
