# Generated by Django 5.1.3 on 2026-10-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0007_playerstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guessattempt',
            options={'ordering': ['attempt_number'], 'verbose_name': 'intento', 'verbose_name_plural': 'intentos'},
        ),
        migrations.AlterModelOptions(
            name='playerstats',
            options={'verbose_name': 'estadísticas de jugador', 'verbose_name_plural': 'estadísticas de jugadores'},
        ),
        migrations.AlterModelOptions(
            name='scoreentry',
            options={'verbose_name': 'puntaje', 'verbose_name_plural': 'puntajes'},
        ),
    ]
