# Generated by Django 5.1.3 on 2026-10-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0007_playerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='name_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
