# Generated by Django 5.1.3 on 2026-10-04 22:51

import gameplay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0009_spanish_names_for_the_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stem',
            name='audio_high',
            field=models.FileField(blank=True, storage=gameplay.models.get_stems_storage, upload_to=gameplay.models.stem_upload_path),
        ),
        migrations.AddField(
            model_name='stem',
            name='audio_low',
            field=models.FileField(blank=True, storage=gameplay.models.get_stems_storage, upload_to=gameplay.models.stem_upload_path),
        ),
    ]
